# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 03:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20171020_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='pics',
            field=models.ManyToManyField(to='core.File'),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_pic',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='story_picture', to='core.File'),
        ),
    ]
