# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171103_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='pics',
        ),
    ]
