# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_story_pics'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='pics',
            field=models.ManyToManyField(to='core.File'),
        ),
    ]
