# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-18 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_story_pics'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='seen',
            field=models.ManyToManyField(to='core.Person'),
        ),
    ]
