# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 08:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_file_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filesize',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='is_optimized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='klass',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='md5sum',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
